In [2]:
'''
Your friends comes up with a fair coin and proposes the following. You will toss the coin untill heads comes up. For each tails you will pay your friend 10$, But if a head comes up your friend will pay you 15$

The sample space of such an experiment looks like this {H, TH, TTH, .... TTTTTH ....}. As soon as a head comes up you stop tossing and your friend pays you 100$. You need to pay your friend 10$ for each tails that came up. So to make a profit you need to get head as quickly as possible.

You can use the simulate a fair coin like we did above. Now you use power of simulation.

Write a simulation logic and a trial logic with which you can decide if you should take this bet or not.

What if your friend offered you 100$ once head comes up? Will you take the bet?

Write a simulation function to decide.'''

'\nYour friends comes up with a fair coin and proposes the following. You will toss the coin untill heads comes up. For each tails you will pay your friend 10$, But if a head comes up your friend will pay you 15$\n\nThe sample space of such an experiment looks like this {H, TH, TTH, .... TTTTTH ....}. As soon as a head comes up you stop tossing and your friend pays you 100$. You need to pay your friend 10$ for each tails that came up. So to make a profit you need to get head as quickly as possible.\n\nYou can use the simulate a fair coin like we did above. Now you use power of simulation.\n\nWrite a simulation logic and a trial logic with which you can decide if you should take this bet or not.\n\nWhat if your friend offered you 100$ once head comes up? Will you take the bet?\n\nWrite a simulation function to decide.'

In [3]:
import random
def coin_toss():
  if random.random() <= 0.5:
    return 0
  return 1

def game():
  give = 0
  recieve = 0
  #tosses = []
  while True:
    toss = coin_toss()
    #tosses.append(toss)
    if(toss == 0):
      give += 10 
      continue
    elif (toss == 1):
      recieve += 15
      break
  #print(tosses)
  return recieve - give

def simulate(n):
  res = []
  for i in range(n):
    res.append(game())
  return sum(res)

In [ ]:
'''
Write a python function to simulate a casino where 2 dice are rolled together and the player wins if there is 
two six and gets 100$. If the casino fee is 5 cents per game, what will be average profit?
'''

In [4]:
import random
def dice_roll():
  dice1 = random.randint(1,6)
  dice2 = random.randint(1,6)
  return dice1 + dice2

def simulate(n):
  rolls = []
  for i in range(n):
    wins = 0
    while dice_roll() != 12:
      wins -= 5

    wins += 100
    rolls.append(wins)
    
  print(sum(rolls)/n)

In [18]:
import pandas as pd

df= pd.read_csv("covid.csv")
df

    patient_id  sex  covid_fast_kit  covid_rt_pcr  actual_diagnostic
0            0    1               0             0                  0
1            1    0               1             0                  0
2            2    0               0             1                  0
3            3    1               1             0                  1
4            4    1               0             0                  0
..         ...  ...             ...           ...                ...
95          95    0               1             0                  0
96          96    0               0             1                  1
97          97    1               1             0                  0
98          98    1               0             1                  1
99          99    1               1             0                  0

[100 rows x 5 columns]

In [33]:
#Probability of testing positive
df[df['actual_diagnostic'] == 1]['actual_diagnostic'].sum()/len(df['actual_diagnostic'])

0.49

In [45]:
#Probability of infected males and females
gender = df.groupby('sex').agg({'actual_diagnostic': sum})
gender['count'] = df.groupby('sex')['sex'].count()
gender['prob_infected'] = gender['actual_diagnostic']/gender['count']
gender

     actual_diagnostic  count  prob_infected
sex
0                   30     66       0.454545
1                   19     34       0.558824

In [54]:
#no of people tested positive using fast kit
fast_kit_positive = df[df['covid_fast_kit'] == 1]['covid_fast_kit'].count()
#no of people that were positive and tested positive using fast kit
actual_diagnostic = df[df['covid_fast_kit'] == 1]['actual_diagnostic'].sum()
#Probability that people were actually positive given they tested positive using fast kit
actual_diagnostic/fast_kit_positive

0.3877551020408163

In [62]:
#no of people actually positive
positive = df[df['actual_diagnostic'] == 1]['actual_diagnostic'].count()
#no of people that tested positive using covide fast kit given they were actually positive
covid_fast_kit_positive = df[df['actual_diagnostic'] == 1]['covid_fast_kit'].sum()
#Probability that people tested positive using fast kit given they were actually positive
covid_fast_kit_positive/positive

0.3877551020408163

In [64]:
#no of people tested positive using rt_pcr kit
rt_pcr_positive = df[df['covid_rt_pcr'] == 1]['covid_rt_pcr'].count()
#no of people that were positive and tested positive using rtpcr kit
actual_diagnostic = df[df['covid_rt_pcr'] == 1]['actual_diagnostic'].sum()
#Probability that people were actually positive given they tested positive using fast kit
actual_diagnostic/rt_pcr_positive

0.68

In [73]:
#no of people actually positive
positive = df[df['actual_diagnostic'] == 1]['actual_diagnostic'].count()
#no of people that tested positive using rtpcr kit given they were actually positive
covid_rt_pcr_positive = df[df['actual_diagnostic'] == 1]['covid_rt_pcr'].sum()
#Probability that people tested positive using rtpcr kit given they were actually positive
covid_rt_pcr_positive/positive

0.6938775510204082

In [2]:
#Spam Classifier
import pandas as pd

sms_spam = pd.read_csv('SMSSpamCollection', sep='\t',
header=None, names=['Label', 'SMS'])
sms_spam

     Label                                                SMS
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [95]:
#Using bayes theorem P(spam|sms) = P(sms|spam)*P(spam)/(P(sms|spam)*P(spam) + P(sms|ham)*P(ham))
p_spam = sms_spam[sms_spam['Label'] == 'spam'].Label.count()/sms_spam['Label'].count()
p_ham = sms_spam[sms_spam['Label'] == 'ham'].Label.count()/sms_spam['Label'].count()
sms_spam['Label'].value_counts(normalize = True)

ham     0.865937
spam    0.134063
Name: Label, dtype: float64

In [3]:
# Randomize the dataset
data_randomized = sms_spam.sample(frac=1, random_state=1)

# Calculate index for split
training_test_index = round(len(data_randomized) * 0.8)

# Split into training and test sets
training_set = data_randomized[:training_test_index].reset_index(drop=True)
test_set = data_randomized[training_test_index:].reset_index(drop=True)

print(training_set.shape)
print(test_set.shape)

(4458, 2)
(1114, 2)

In [4]:
# After cleaning
training_set['SMS'] = training_set['SMS'].str.replace(
   '\W', ' ') # Removes punctuation #\W matches characters which is not a word character [^a-zA-Z0-9_]
training_set['SMS'] = training_set['SMS'].str.lower()
training_set

/var/folders/2r/xxqxvqqd73q6nvbwth8rkt5h0000gn/T/ipykernel_53725/2791903031.py:2: FutureWarning: The default value of regex will change from True to False in a future version.
  training_set['SMS'] = training_set['SMS'].str.replace(

     Label                                                SMS
0      ham                       yep  by the pretty sculpture
1      ham      yes  princess  are you going to make me moan
2      ham                         welp apparently he retired
3      ham                                            havent
4      ham  i forgot 2 ask ü all smth   there s a card on ...
...    ...                                                ...
4453   ham  sorry  i ll call later in meeting any thing re...
4454   ham  babe  i fucking love you too    you know  fuck...
4455  spam  u ve been selected to stay in 1 of 250 top bri...
4456   ham  hello my boytoy     geeee i miss you already a...
4457   ham                           wherre s my boytoy

[4458 rows x 2 columns]

In [120]:
#Creating a vocabulary
vocabulary = {}
for i in training_set['SMS']:
    words = i.split(' ')
    for word in words:
        if word not in vocabulary.keys():
            vocabulary[word] = 1
        else:
            vocabulary[word] +=1
len(vocabulary.keys())

7784

In [5]:
#creating vocabulary as a list
training_set['SMS'] = training_set['SMS'].str.split()

vocabulary = []
for sms in training_set['SMS']:
   for word in sms:
      vocabulary.append(word)

vocabulary = list(set(vocabulary))

In [6]:
word_counts_per_sms = {unique_word: [0] * len(training_set['SMS']) for unique_word in vocabulary}

for index,sms in enumerate(training_set['SMS']):
    for word in sms:
        word_counts_per_sms[word][index] = 1

In [7]:
word_counts = pd.DataFrame(word_counts_per_sms)
word_counts

,epsilon,shut,attended,evn,common,wkg,talked,lifeis,expects,jewelry,...,bulbs,kisi,piss,doggy,bmw,08002986906,murderer,awarded,auntie,needing
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4453,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4454,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4455,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4456,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4457,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [8]:
training_set_clean = pd.concat([training_set, word_counts], axis=1)
training_set_clean

,Label,SMS,epsilon,shut,attended,evn,common,wkg,talked,lifeis,...,bulbs,kisi,piss,doggy,bmw,08002986906,murderer,awarded,auntie,needing
0,ham,"[yep, by, the, pretty, sculpture]",0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,ham,"[yes, princess, are, you, going, to, make, me,...",0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,ham,"[welp, apparently, he, retired]",0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,ham,[havent],0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,ham,"[i, forgot, 2, ask, ü, all, smth, there, s, a,...",0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4453,ham,"[sorry, i, ll, call, later, in, meeting, any, ...",0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4454,ham,"[babe, i, fucking, love, you, too, you, know, ...",0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4455,spam,"[u, ve, been, selected, to, stay, in, 1, of, 2...",0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4456,ham,"[hello, my, boytoy, geeee, i, miss, you, alrea...",0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4457,ham,"[wherre, s, my, boytoy]",0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [9]:
# Isolating spam and ham messages first
spam_messages = training_set_clean[training_set_clean['Label'] == 'spam']
ham_messages = training_set_clean[training_set_clean['Label'] == 'ham']

# P(Spam) and P(Ham) in training set
p_spam = len(spam_messages) / len(training_set_clean)
p_ham = len(ham_messages) / len(training_set_clean)

# N_Spam
n_spam = len(spam_messages)

# N_Ham

n_ham = len(ham_messages)

# N_Vocabulary
n_vocabulary = len(vocabulary)

# Laplace smoothing
alpha = 1

In [18]:
''' 𝑃(𝑤𝑖|𝑆𝑝𝑎𝑚)=𝑁𝑖|𝑆𝑝𝑎𝑚+𝛼/𝑁𝑠𝑝𝑎𝑚+𝛼.𝑁𝑣 

    𝑃(𝑤𝑖|𝐻𝑎𝑚)=𝑁𝑖|𝐻𝑎𝑚+𝛼/𝑁ℎ𝑎𝑚+𝛼.𝑁𝑣  '''

# Initiate parameters
# parameters_spam[word] will give probability of word occuring in spam email
parameters_spam = {unique_word:0 for unique_word in vocabulary}
# parameters_ham[word] will give probability of word occuring in ham email
parameters_ham = {unique_word:0 for unique_word in vocabulary}

# Calculate parameters
for word in vocabulary:
    # Ni|Spam + alpha 
    n_word_given_spam = spam_messages[word].sum() # spam_messages already defined
    # P(wi|Spam)
    p_word_given_spam = (n_word_given_spam + alpha) / (n_spam + alpha*n_vocabulary)
    parameters_spam[word] = p_word_given_spam

    # Ni|Ham + alpha 
    n_word_given_ham = ham_messages[word].sum() # ham_messages already defined
    # P(wi|Ham)
    p_word_given_ham = (n_word_given_ham + alpha) / (n_ham + alpha*n_vocabulary)
    parameters_ham[word] = p_word_given_ham

In [45]:
import re

# message : string
def spam_detector(message):
   
    message = re.sub('\W','', message)
    message = message.lower().split()

    p_spam_given_message = p_spam
    p_ham_given_message = p_ham

    for word in message:
        if word in parameters_spam:
            # p(Spam|word) = p(spam) * p(word|spam) = prior * likelihood
            p_spam_given_message *= parameters_spam[word]

        if word in parameters_ham:
            p_ham_given_message *= parameters_ham[word]


    p_given_message = p_spam_given_message + p_ham_given_message

    # p(Spam|word) = (p(spam) * p(word|spam)) / p(word) 
    p_spam_given_message = p_spam_given_message/p_given_message

    p_ham_given_message = p_ham_given_message/p_given_message

    #print('P(Spam|message):', p_spam_given_message)
    #print('P(Ham|message):', p_ham_given_message)

    if p_ham_given_message > p_spam_given_message:
        return 'ham'
    elif p_ham_given_message < p_spam_given_message:
        return 'spam'
    else:
        return 'Equal proabilities, needs human classification'

In [46]:
spam_detector('WINNER!! This is the secret code to unlock the money: C3421.')

'ham'

In [54]:
test_set['Predicted'] = test_set['SMS'].apply(spam_detector)
test_set[test_set['Predicted'] == 'ham']

     Label                                                SMS Predicted
0      ham          Later i guess. I needa do mcat study too.       ham
1      ham             But i haf enuff space got like 4 mb...       ham
2     spam  Had your mobile 10 mths? Update to latest Oran...       ham
3      ham  All sounds good. Fingers . Makes it difficult ...       ham
4      ham  All done, all handed in. Don't know if mega sh...       ham
...    ...                                                ...       ...
1109   ham  We're all getting worried over here, derek and...       ham
1110   ham  Oh oh... Den muz change plan liao... Go back h...       ham
1111   ham  CERI U REBEL! SWEET DREAMZ ME LITTLE BUDDY!! C...       ham
1112  spam  Text & meet someone sexy today. U can find a d...       ham
1113   ham                            K k:) sms chat with me.       ham

[1114 rows x 3 columns]

In [56]:
correct = 0
total = test_set.shape[0]

for row in test_set.iterrows():
    row = row[1]
    if row['Label'] == row['Predicted']:
        correct += 1

print('Correct:', correct)
print('Incorrect:', total - correct)
print('Accuracy:', correct/total)

Correct: 967
Incorrect: 147
Accuracy: 0.8680430879712747